[package]
name = "try_with_timeout"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = {version = "1.49.0", features = ["full"]}
thiserror = {version = "2.0.18"}
log = {version = "0.4.29"}
simple_logger = {version = "5.1.0"}
